"""Generate .story/knowledge/ overview files from confirmed scope.

Writes product.yaml, manifest.yaml, search-catalog.md, index stubs,
candidate domains, and pending-review-items.md.
"""

from __future__ import annotations

import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path

from .detector import DetectionResult
from .paths import (
    declarations_dir,
    graph_json_path,
    indexes_dir,
    manifest_path,
    product_path,
    reviews_dir,
    search_catalog_path,
)
from .scaffold import scaffold_knowledge_dir
from .scope import ScopeRecommendation


def generate_knowledge_files(
    workspace: str | Path,
    detection: DetectionResult,
    scope: ScopeRecommendation,
) -> list[str]:
    """Generate all knowledge overview files. Returns list of created file paths."""
    ws = Path(workspace)
    scaffold_knowledge_dir(ws)
    created: list[str] = []

    created.append(_write_product_yaml(ws, detection))
    created.append(_write_manifest_yaml(ws, detection, scope))
    created.append(_write_search_catalog(ws, detection, scope))
    created.extend(_write_index_stubs(ws, scope))
    created.append(_write_product_context_graph(ws, detection, scope))
    created.append(_write_candidate_domains(ws, scope))
    created.append(_write_pending_review_items(ws, scope))

    return created


def _get_git_info(ws: Path) -> dict:
    """Get git commit and dirty state."""
    info: dict = {"commit": "unknown", "dirty": False, "timestamp": ""}
    try:
        r = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            cwd=str(ws),
            timeout=10,
        )
        if r.returncode == 0:
            info["commit"] = r.stdout.strip()
    except Exception:
        pass
    try:
        r = subprocess.run(
            ["git", "status", "--porcelain"],
            capture_output=True,
            text=True,
            cwd=str(ws),
            timeout=10,
        )
        if r.returncode == 0 and r.stdout.strip():
            info["dirty"] = True
    except Exception:
        pass
    info["timestamp"] = datetime.now(tz=timezone.utc).isoformat()
    return info


def _write_product_yaml(ws: Path, detection: DetectionResult) -> str:
    """Write product.yaml."""
    path = product_path(ws)
    lines = [
        f"name: {detection.product_guess}",
        f"display_name: {_display_name(detection.product_guess)}",
        f"root: {detection.root.replace(chr(92), '/')}",
        "",
        "services:",
    ]
    for svc in detection.services:
        lines.append(f"  - id: {svc.id}")
        lines.append(f"    path: {svc.path.replace(chr(92), '/')}")
        lines.append(f"    type: {svc.type}")
    if detection.frontends:
        lines.extend(["", "frontends:"])
        for fe in detection.frontends:
            lines.append(f"  - id: {fe.id}")
            lines.append(f"    path: {fe.path.replace(chr(92), '/')}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return str(path)


def _write_manifest_yaml(
    ws: Path,
    detection: DetectionResult,
    scope: ScopeRecommendation,
) -> str:
    """Write manifest.yaml."""
    path = manifest_path(ws)
    git = _get_git_info(ws)

    lines = [
        "version: 1",
        "",
        "product:",
        f"  name: {detection.product_guess}",
        "",
        "source:",
        f"  commit: {git['commit'][:12]}",
        f"  timestamp: {git['timestamp']}",
        f"  dirty: {str(git['dirty']).lower()}",
        "",
        "status: initialized",
        "",
        "domains:",
    ]
    for svc in scope.included:
        lines.append(f"  - {svc.id}")
    lines.extend(["", "sources:"])
    for svc in scope.included:
        lines.append(f"  - id: {svc.id}")
        lines.append("    type: git-or-local-service")
        lines.append(f"    path: {svc.path.replace(chr(92), '/')}")
        lines.append("    included: true")
    for svc in scope.excluded:
        lines.append(f"  - id: {svc.id}")
        lines.append(
            f"    type: {'frontend-app' if 'frontend' in svc.type else 'service'}"
        )
        lines.append(f"    path: {svc.path.replace(chr(92), '/')}")
        lines.append("    included: false")
        lines.append("    phase: P1")

    lines.extend(["", "stats:"])
    for key, count in detection.file_stats.items():
        lines.append(f"  {key}: {count}")

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return str(path)


def _write_search_catalog(
    ws: Path,
    detection: DetectionResult,
    scope: ScopeRecommendation,
) -> str:
    """Write search-catalog.md."""
    path = search_catalog_path(ws)
    lines = [
        f"# Search Catalog — {detection.product_guess}",
        "",
        "Auto-generated by `story project init-knowledge`.",
        "",
        "## Services",
        "",
    ]
    for svc in scope.included:
        lines.append(f"- **{svc.id}** ({svc.type})")
    if scope.excluded:
        lines.extend(["", "## Excluded (P1)", ""])
        for svc in scope.excluded:
            lines.append(f"- {svc.id}")

    lines.extend(["", "## Candidate Domains", ""])
    for cd in scope.candidate_domains:
        lines.append(f"- **{cd.domain}** ({cd.source_service})")
        for sc in cd.candidate_scenarios:
            lines.append(f"  - {sc}")

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return str(path)


def _write_index_stubs(ws: Path, scope: ScopeRecommendation) -> list[str]:
    """Write empty index stubs for each included service."""
    idx_dir = indexes_dir(ws)
    idx_dir.mkdir(parents=True, exist_ok=True)
    created: list[str] = []

    stub_names = ["service-index.md", "api-index.md", "table-index.md", "mq-index.md"]
    for name in stub_names:
        p = idx_dir / name
        if not p.exists():
            title = name.replace("-", " ").replace(".md", "").title()
            p.write_text(f"# {title}\n\nPending deep scan.\n", encoding="utf-8")
            created.append(str(p))

    return created


def _write_product_context_graph(
    ws: Path,
    detection: DetectionResult,
    scope: ScopeRecommendation,
) -> str:
    """Write initial product-context-graph.json."""
    path = graph_json_path(ws)
    path.parent.mkdir(parents=True, exist_ok=True)

    graph = {
        "apiVersion": "knowledge/v1",
        "kind": "ProductContextGraph",
        "product": detection.product_guess,
        "nodes": [
            {
                "id": svc.id,
                "type": "service",
                "label": svc.id,
                "service_type": svc.type,
            }
            for svc in scope.included
        ],
        "edges": [],
        "meta": {
            "status": "skeleton",
            "note": "Edges and details pending scenario deep scan",
        },
    }
    path.write_text(
        json.dumps(graph, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    return str(path)


def _write_candidate_domains(ws: Path, scope: ScopeRecommendation) -> str:
    """Write candidate domains to declarations."""
    ddir = declarations_dir(ws)
    ddir.mkdir(parents=True, exist_ok=True)
    path = ddir / "candidate-domains.yaml"

    lines = [
        "# Candidate domains — NOT final boundaries.",
        "# Confirm via: story project scenarios review",
        "",
    ]
    for cd in scope.candidate_domains:
        lines.append(f"- domain: {cd.domain}")
        lines.append(f"  source_service: {cd.source_service}")
        lines.append("  status: candidate")
        lines.append("  candidate_scenarios:")
        for sc in cd.candidate_scenarios:
            lines.append(f"    - {sc}")
        lines.append("")

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return str(path)


def _write_pending_review_items(ws: Path, scope: ScopeRecommendation) -> str:
    """Write pending-review-items.md."""
    rdir = reviews_dir(ws)
    rdir.mkdir(parents=True, exist_ok=True)
    path = rdir / "pending-review-items.md"

    lines = [
        "# Pending Review Items",
        "",
        "These items need user confirmation before becoming formal knowledge.",
        "",
        "## Candidate Domains",
        "",
    ]
    for cd in scope.candidate_domains:
        lines.append(
            f"- [ ] **{cd.domain}** — confirm scenarios: {', '.join(cd.candidate_scenarios)}"
        )
    lines.extend(["", "## Next Steps", ""])
    lines.append("```bash")
    lines.append("story project scenarios review")
    for cd in scope.candidate_domains[:3]:
        lines.append(f"story project scenario scan {cd.domain}")
    lines.append("```")

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return str(path)


def _display_name(guess: str) -> str:
    """Convert product guess to display name."""
    return guess.replace("-", " ").title()
